#Determinant

In [47]:
import numpy as np
import copy
from math import sqrt
import numpy as np 
import sympy as sp
from sympy import * 

def det(a):
    
    if len(a) ==1: # if size =1
        d = a[0]
        return d
    elif len(a)==2:
        d = a[0][0]*a[1][1] - a[1][0]*a[0][1] #if size =2
        return d
    else:
        d = 0
        for i in range(len(a[0])):
            s_m=np.delete(np.delete(a,0,0),i,1)
            d += ((-1)**i)*a[0][i]*det((s_m)) #if size >2

        return d
# testing 
A = [5]
B = [[2,9],[6,5]]
C = [[2,9,0],[6,5,1],[9,3,7]]
D = [[2,9,0,5],[6,5,5,1],[9,4,3,7],[5,4,5,3]]

print("The determinant of the Matrix A is:  ", det(A))
print("The determinant of the Matrix A is:  ", det(B))
print("The determinant of the Matrix A is:  ", det(C))
print("The determinant of the Matrix A is:  ", det(D))


The determinant of the Matrix A is:   5
The determinant of the Matrix A is:   -44
The determinant of the Matrix A is:   -233
The determinant of the Matrix A is:   800


#Trace

In [5]:
print("TRACE                ")      
def trace(a):
  return (sum(np.diag(a)))
# testing 
A = [5]
B = [[2,9],[6,5]]
C = [[2,9,0],[6,5,1],[9,3,7]]

print("The trace of the Matrix A is:  ", trace(A))
print("The trace of the Matrix A is:  ", trace(B))
print("The trace of the Matrix A is:  ", trace(C))

TRACE                
The trace of the Matrix A is:   [5]
The trace of the Matrix A is:   7
The trace of the Matrix A is:   14


#Eigenspace

In [15]:

print("Eigenvalues/Eigenvectors")
def eigenD(matrix):
   l = len(matrix) #M 
   eye = np.eye(l,l) # I matrix 
   lmbda= sp.Symbol('lda') 
   m= matrix - (lmbda*eye) 
   pa=det(m) # calculate determinant 
   pa_sol=sp.Symbol.cancel(pa) # charecstic polynomial
   ldt=sp.solve(pa,lmbda) 
   ldt=np.sort(ldt)
   print("Eigenvalues are: ",ldt) 
   for i in ldt:
     #print(' calculating eigen vector of lambda : ', i)
     m= matrix - (i*eye) 
     M=Matrix(m) 
     M_rref = M.rref()  # rref 
     rrf=M_rref[0] 
     rrf=np.array(rrf) 
     eye=np.array(eye)
     for i in range(rrf.shape[0]):
       if rrf[i][i]==0:
         rrf[i][i]= -1 
     for i in range(rrf.shape[1]):
          if np.array_equal(rrf[:,i], eye[:,i]) :
            pass
          else:
            print(' eigen vectors are \n',-1*rrf[:,i])
           
A = [[1, 2, 1],
    [0, -5, 0],
      [1, 8, 1]]    
       
eigenD(A)       

Eigenvalues/Eigenvectors
Eigenvalues are:  [-5.00000000000000 0.0 2.00000000000000]
 eigen vectors are 
 [0.0869565217391304 -0.760869565217391 1]
 eigen vectors are 
 [-1 0 1]
 eigen vectors are 
 [1.00000000000000 0 1]


#LU decomposition

##Crout

In [27]:
import numpy as np
from cmath import e

def crout(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))
    for j in range(n):
        U[j][j] = 1             # set the j,j-th entry of U to 1
        for i in range(j, n):  # starting at L[j][j], solve j-th column of L
            alpha = float(A[i][j])
            for k in range(j):
                alpha -= L[i][k]*U[k][j]
            L[i][j] = alpha
        for i in range(j+1, n):# starting at U[j][j+1], solve j-th row of U
            tempU = float(A[j][i])
            for k in range(j):
                tempU -= L[j][k]*U[k][i]
            if int(L[j][j]) == 0:
                L[j][j] = e-40
            U[j][i] = tempU/L[j][j]

    return 'L ; ' , L, 'U : ' , U ,'L@U : ' , L@U
mat =np.array([[1, 3, 5],
	 [0, 4, 6],
	  [0, 2, 4]])
crout(mat)

('L ; ',
 array([[1., 0., 0.],
        [0., 4., 0.],
        [0., 2., 1.]]),
 'U : ',
 array([[1. , 3. , 5. ],
        [0. , 1. , 1.5],
        [0. , 0. , 1. ]]),
 'L@U : ',
 array([[1., 3., 5.],
        [0., 4., 6.],
        [0., 2., 4.]]))

In [28]:
mat =np.array([[2, -1, -2],
	[-4, 7, 3],
	[-4, -2, 8]])
crout(mat)

('L ; ',
 array([[ 2. ,  0. ,  0. ],
        [-4. ,  5. ,  0. ],
        [-4. , -4. ,  3.2]]),
 'U : ',
 array([[ 1. , -0.5, -1. ],
        [ 0. ,  1. , -0.2],
        [ 0. ,  0. ,  1. ]]),
 'L@U : ',
 array([[ 2., -1., -2.],
        [-4.,  7.,  3.],
        [-4., -2.,  8.]]))

##Gaussian E

In [29]:
def LU_decomposition(A):
    import numpy as np
    if type(A) != np.ndarray:
        raise TypeError('Input must be a numpy array, type {} will not work'.format(type(A)))
    if np.shape(A)[0] != np.shape(A)[1]:
        raise ValueError('Input matrix is not square, shape {} will not work'.format(np.shape(A)))
    L = np.zeros_like(A, dtype=float)
    U = np.zeros_like(A, dtype=float)
    N = np.size(A, 0) #rows
    for k in range(N):
        L[k, k] = 1 
        U[k, k] = A[k, k] - np.dot(L[k, :k], U[:k, k])
        
        for j in range(k+1, N):
            U[k, j] = A[k, j] - np.dot(L[k, :k], U[:k, j])
        for i in range(k+1, N):
            L[i, k] = (A[i, k] - np.dot(L[i, :k], U[:k, k])) / U[k, k]
    return A, L, U, L@U
LU_decomposition(mat)

(array([[ 2, -1, -2],
        [-4,  7,  3],
        [-4, -2,  8]]),
 array([[ 1. ,  0. ,  0. ],
        [-2. ,  1. ,  0. ],
        [-2. , -0.8,  1. ]]),
 array([[ 2. , -1. , -2. ],
        [ 0. ,  5. , -1. ],
        [ 0. ,  0. ,  3.2]]),
 array([[ 2., -1., -2.],
        [-4.,  7.,  3.],
        [-4., -2.,  8.]]))

In [30]:
mat =np.array([[6, 18, 3],
	 [2, 12, 1],
	  [4, 15, 3]])
LU_decomposition(mat)

(array([[ 6, 18,  3],
        [ 2, 12,  1],
        [ 4, 15,  3]]),
 array([[1.        , 0.        , 0.        ],
        [0.33333333, 1.        , 0.        ],
        [0.66666667, 0.5       , 1.        ]]),
 array([[ 6., 18.,  3.],
        [ 0.,  6.,  0.],
        [ 0.,  0.,  1.]]),
 array([[ 6., 18.,  3.],
        [ 2., 12.,  1.],
        [ 4., 15.,  3.]]))

#SVD decomposition

In [31]:
def my_SVD0(A):
    # rows of A
    m = A.shape[0]
    # columns of A
    n = A.shape[1]
    
    # Find Eigenvectors of AA_T
    Uw, U = np.linalg.eig(A.dot(A.T))

    # Sort the eigenvalue and eigenvector
    idx = Uw.argsort()[::-1]   
    Uw = Uw[idx]
    U = U[:,idx]
    
    # Find Eigenvectors of A_TA
    Vw, V = np.linalg.eig(A.T.dot(A))
    # Sort the eigenvalue and eigenvector
    idx = Vw.argsort()[::-1]   
    Vw = Vw[idx]
    V = V[:,idx]

    # Choose the smaller dimension size
    w = Uw if m<n else Vw
    # Make small negative value zero
    w[np.where(w<0)] = 1e-30
    w = np.sqrt(w)
    # Find the amount of non-zero singular value
    #non_zero_eig = w[np.where(w>1e-10)].size
    
    # Sigma
    S = np.zeros((m,n))
    np.fill_diagonal(S, w)
    
    # w * w_r = 1 
    w_r = np.reciprocal(w)
    if m>n:
        # Inverse of Sigma
        S_inv = np.zeros((n,m))
        np.fill_diagonal(S_inv, w_r)
        # Calculalte U by A V S_inv
        U = A.dot(V).dot(S_inv)
        
    else:
        # Inverse of Sigma_T
        S_T_inv = np.zeros((m,n))
        np.fill_diagonal(S_T_inv, w_r)
        # Calculate V by A_T U S_T_inv
        V = A.T.dot(U).dot(S_T_inv)
        

    
    return U, S, V.T , np.round(U@S@V.T)
A =np.array([[1, 0, 1,0],
    [0, 1,0, 1]])

my_SVD0(A)

(array([[0., 1.],
        [1., 0.]]),
 array([[1.41421356, 0.        , 0.        , 0.        ],
        [0.        , 1.41421356, 0.        , 0.        ]]),
 array([[0.        , 0.70710678, 0.        , 0.70710678],
        [0.70710678, 0.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ]]),
 array([[1., 0., 1., 0.],
        [0., 1., 0., 1.]]))

In [41]:
import numpy as np

def make_orthogonal(matrix, non_zero_eig):
    dim = matrix.shape[0]
    
    if non_zero_eig == dim:
        return matrix
    
    Q, _ = np.linalg.qr(matrix[:, :non_zero_eig])
    
    matrix[:, non_zero_eig:non_zero_eig+1] = Q[:, -1:]
    matrix[:, non_zero_eig:non_zero_eig+1] /= np.linalg.norm(matrix[:, non_zero_eig:non_zero_eig+1], axis=0)
    
    return make_orthogonal(matrix, non_zero_eig+1)


In [42]:
import numpy as np
from sympy import symbols
from sympy.solvers import solve

def my_SVD(A):
    # rows of A
    m = A.shape[0]
    # columns of A
    n = A.shape[1]
    
    # Find Eigenvectors of AA_T
    Uw, U = np.linalg.eig(A.dot(A.T))
    # Sort the eigenvalue and eigenvector
    idx = Uw.argsort()[::-1]   
    Uw = Uw[idx]
    U = U[:,idx]
    
    # Find Eigenvectors of A_TA
    Vw, V = np.linalg.eig(A.T.dot(A))
    # Sort the eigenvalue and eigenvector
    idx = Vw.argsort()[::-1]   
    Vw = Vw[idx]
    V = V[:,idx]

    # Choose the smaller dimension size
    w = Uw if m<n else Vw
    # Make small negative value  griba l zero, zero
    w[np.where(w<0)] = 1e-30
    #bcz mygderch y70t sqrt fiha negative value
    w = np.sqrt(w)
    # Find the amount of non-zero singular value
    non_zero_eig = w[np.where(w>1e-10)].size
    
    # Sigma
    S = np.zeros((m,n))
    #n7oto fi diagonal sigmatt li kheyrnahm 
    np.fill_diagonal(S, w)
    
    # w * w_r = 1
    w_r = np.reciprocal(w)
    if m>n:
        #if 3dd lignes > mn 3dd cols
        # Inverse of Sigma
        S_inv = np.zeros((n,m))
        np.fill_diagonal(S_inv, w_r)
        # Calculalte U by A V S_inv
        U = A.dot(V).dot(S_inv)
        
    else:
        # Inverse of Sigma_T
        S_T_inv = np.zeros((m,n))
        np.fill_diagonal(S_T_inv, w_r)
        # Calculate V by A_T U S_T_inv
        V = A.T.dot(U).dot(S_T_inv)
        
    # Make U orthogonal
    U = make_orthogonal(U, non_zero_eig)
     # Make V orthogonal
    V = make_orthogonal(V, non_zero_eig)
    
    return U, S, V.T , np.round(U@S@V.T)
A =np.array([[1, 0, 1,0],
    [0, 1,0, 1]])

my_SVD(A)


(array([[0., 1.],
        [1., 0.]]),
 array([[1.41421356, 0.        , 0.        , 0.        ],
        [0.        , 1.41421356, 0.        , 0.        ]]),
 array([[ 0.00000000e+00,  7.07106781e-01,  0.00000000e+00,
          7.07106781e-01],
        [ 7.07106781e-01,  0.00000000e+00,  7.07106781e-01,
          0.00000000e+00],
        [ 7.07106781e-01,  1.11022302e-16,  7.07106781e-01,
          1.11022302e-16],
        [ 3.04737854e-01, -6.38071187e-01, -3.04737854e-01,
          6.38071187e-01]]),
 array([[1., 0., 1., 0.],
        [0., 1., 0., 1.]]))

In [43]:
A = np.array([[1, 1, 1],
    [-1, -3, -3],
      [2, 4,4]]   ) 
         
my_SVD(A)

(array([[-0.21821511,  0.78679656, -0.78679656],
        [ 0.57227826,  0.58237811, -0.58237811],
        [-0.79049337,  0.20441846, -0.20441846]]),
 array([[7.58836029e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 6.45591314e-01, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 6.28036983e-16]]),
 array([[-0.31251549, -0.67168969, -0.67168969],
        [ 0.94991267, -0.22098182, -0.22098182],
        [ 0.94991267, -0.22098182, -0.22098182]]),
 array([[ 1.,  1.,  1.],
        [-1., -3., -3.],
        [ 2.,  4.,  4.]]))